pipeline {
  agent any

  environment {
    AWS_REGION = "ap-south-1"
    ECR_REPO = "<ACCOUNT_ID>.dkr.ecr.ap-south-1.amazonaws.com/nginx-app"
    CLUSTER_NAME = "<EKS_CLUSTER_NAME>"
  }

  stages {

    stage('Checkout Code') {
      steps {
        git branch: 'main',
            url: 'https://github.com/ssing56/aws-eks-nginx-deployment.git'
      }
    }

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t nginx-app .'
      }
    }

    stage('Login to ECR') {
      steps {
        sh '''
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin $ECR_REPO
        '''
      }
    }

    stage('Tag & Push Image') {
      steps {
        sh '''
          docker tag nginx-app:latest $ECR_REPO:latest
          docker push $ECR_REPO:latest
        '''
      }
    }

    stage('Update Kubeconfig') {
      steps {
        sh '''
          aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name $CLUSTER_NAME
        '''
      }
    }

    stage('Deploy to EKS') {
      steps {
        sh 'kubectl apply -f k8s/'
      }
    }
  }
}
